services:
  api:
    build:
      context: ../..
      dockerfile: docker/app/Dockerfile

    container_name: mercadinho-api

    ports:
      - '3000:3000'

    environment:
      NODE_ENV: development

      PORT: 3000

      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres?schema=public

      REDIS_HOST: redis
      REDIS_PORT: 6379

    volumes:
      - ../../:/app
      - /app/node_modules

    restart: unless-stopped

    depends_on:
      - postgres
      - redis

    networks:
      - mercadinho-network

networks:
  mercadinho-network:
    driver: bridge