services:
  redis:
    image: redis:8-alpine

    container_name: mercadinho-redis

    ports:
      - '6379:6379'

    volumes:
      - redis_data:/data

    restart: unless-stopped

    networks:
      - mercadinho-network

volumes:
  redis_data:

networks:
  mercadinho-network:
    driver: bridge