allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: true
  prisma: true
  unrs-resolver: true
# pnpm-workspace.yaml
onlyBuiltDependencies:
  - prisma
  - "@prisma/client"
  - "@prisma/engines"
  - esbuild
  - unrs-resolver
