name: CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup PNPM
        uses: pnpm/action-setup@v5
        with:
          version: 11
        
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prisma Generate
        run: pnpm prisma generate

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Tests
        run: pnpm test

      - name: Docker Build Validation
        run: docker build -f docker/app/Dockerfile .